//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public string auto { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string rif { get; set; }
        public string telefono { get; set; }
        public string sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public string nit { get; set; }
        public string contacto { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string registro { get; set; }
        public string codigo { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string codigo_postal { get; set; }
        public decimal tasa1 { get; set; }
        public decimal tasa2 { get; set; }
        public decimal tasa3 { get; set; }
        public decimal retencion_iva { get; set; }
        public decimal retencion_islr { get; set; }
        public decimal factor_cambio { get; set; }
        public decimal debito_bancario { get; set; }
        public string solicita { get; set; }
        public string recibe { get; set; }
        public string precio_1 { get; set; }
        public string precio_2 { get; set; }
        public string precio_3 { get; set; }
        public string precio_4 { get; set; }
        public string precio_5 { get; set; }
    }
}
