//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_series_fiscales
    {
        public string auto { get; set; }
        public string serie { get; set; }
        public int correlativo { get; set; }
        public string estatus_factura { get; set; }
        public string estatus_nd { get; set; }
        public string estatus_nc { get; set; }
        public string estatus_ne { get; set; }
        public string estatus { get; set; }
        public string control { get; set; }
    }
}
