//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_sucursal_ext
    {
        public string auto_sucursal { get; set; }
        public string es_activo { get; set; }
        public string estatus_fact_credito { get; set; }
    
        public virtual empresa_sucursal empresa_sucursal { get; set; }
    }
}
