//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_depositos_ext
    {
        public string auto_deposito { get; set; }
        public string es_predeterminado { get; set; }
        public string es_activo { get; set; }
    }
}
