//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_grupo_ext
    {
        public string auto_empresaGrupo { get; set; }
        public int idEmpresaHndPrecio { get; set; }
        public string estatus { get; set; }
    
        public virtual empresa_grupo empresa_grupo { get; set; }
        public virtual empresa_hnd_precios empresa_hnd_precios { get; set; }
    }
}
