//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemaEntities : DbContext
    {
        public sistemaEntities()
            : base("name=sistemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cxp> cxp { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<empresa_cobradores> empresa_cobradores { get; set; }
        public virtual DbSet<empresa_depositos> empresa_depositos { get; set; }
        public virtual DbSet<empresa_depositos_ext> empresa_depositos_ext { get; set; }
        public virtual DbSet<empresa_hnd_precios> empresa_hnd_precios { get; set; }
        public virtual DbSet<empresa_series_fiscales> empresa_series_fiscales { get; set; }
        public virtual DbSet<empresa_sucursal> empresa_sucursal { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_costos> productos_costos { get; set; }
        public virtual DbSet<productos_ext> productos_ext { get; set; }
        public virtual DbSet<productos_precios> productos_precios { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<reconversion_monetaria> reconversion_monetaria { get; set; }
        public virtual DbSet<sistema_configuracion> sistema_configuracion { get; set; }
        public virtual DbSet<sistema_funciones> sistema_funciones { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<usuarios_grupo> usuarios_grupo { get; set; }
        public virtual DbSet<vendedores> vendedores { get; set; }
        public virtual DbSet<sistema_contadores> sistema_contadores { get; set; }
        public virtual DbSet<empresa_grupo> empresa_grupo { get; set; }
        public virtual DbSet<empresa_grupo_ext> empresa_grupo_ext { get; set; }
        public virtual DbSet<empresa_sucursal_ext> empresa_sucursal_ext { get; set; }
    }
}
