//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_ext
    {
        public string auto_producto { get; set; }
        public string auto_precio_may_1 { get; set; }
        public string auto_precio_may_2 { get; set; }
        public string auto_precio_may_3 { get; set; }
        public int contenido_may_1 { get; set; }
        public int contenido_may_2 { get; set; }
        public int contenido_may_3 { get; set; }
        public decimal utilidad_may_1 { get; set; }
        public decimal utilidad_may_2 { get; set; }
        public decimal utilidad_may_3 { get; set; }
        public decimal precio_may_1 { get; set; }
        public decimal precio_may_2 { get; set; }
        public decimal precio_may_3 { get; set; }
        public decimal pdmf_1 { get; set; }
        public decimal pdmf_2 { get; set; }
        public decimal pdmf_3 { get; set; }
    }
}
