//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class reconversion_monetaria
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string idUsuario { get; set; }
        public string codigo_usuario { get; set; }
        public string usuario { get; set; }
        public decimal factor_reconversion { get; set; }
        public decimal factor_divisa { get; set; }
        public int items_afectados { get; set; }
        public int proveedores_afectados { get; set; }
        public int saldos_por_pagar_afectados { get; set; }
        public string equipo_estacion { get; set; }
    }
}
