//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_contadores
    {
        public int a_clientes_grupo { get; set; }
        public int a_usuarios { get; set; }
        public int a_empresa_series_fiscales { get; set; }
        public int a_empresa_depositos { get; set; }
        public int a_empresa_medios { get; set; }
        public int a_empresa_cobradores { get; set; }
        public int a_empresa_transporte { get; set; }
        public int a_clientes { get; set; }
        public int a_sistema_estados { get; set; }
        public int a_clientes_zonas { get; set; }
        public int a_proveedores_grupo { get; set; }
        public int a_proveedores { get; set; }
        public int a_productos_grupo { get; set; }
        public int a_productos_subgrupo { get; set; }
        public int a_productos_marca { get; set; }
        public int a_productos_medida { get; set; }
        public int a_productos_conceptos { get; set; }
        public int a_empresa_departamentos { get; set; }
        public int a_productos { get; set; }
        public int a_empresa_tasas { get; set; }
        public int a_productos_movimientos { get; set; }
        public int a_productos_movimientos_cargos { get; set; }
        public int a_empresa_agencias { get; set; }
        public int a_cxc { get; set; }
        public int a_cxc_nd { get; set; }
        public int a_cxc_nc { get; set; }
        public int a_cxc_chq { get; set; }
        public int a_cxc_recibo { get; set; }
        public int a_cxc_recibo_numero { get; set; }
        public int a_ventas { get; set; }
        public int a_cxp { get; set; }
        public int a_cxp_nd { get; set; }
        public int a_cxp_nc { get; set; }
        public int a_cxp_chq { get; set; }
        public int a_cxp_recibo { get; set; }
        public int a_cxp_recibo_numero { get; set; }
        public int a_compras { get; set; }
        public int a_ventas_presupuesto { get; set; }
        public int a_ventas_pedido { get; set; }
        public int a_sistema_transito { get; set; }
        public int a_ventas_retenciones { get; set; }
        public int a_ventas_despacho { get; set; }
        public int a_cxc_anticipo { get; set; }
        public int a_cxp_anticipo { get; set; }
        public int a_productos_movimientos_descargos { get; set; }
        public int a_productos_movimientos_traslados { get; set; }
        public int a_productos_movimientos_ajustes { get; set; }
        public int a_compras_orden { get; set; }
        public int a_compras_retenciones { get; set; }
        public int a_clientes_afiliados { get; set; }
        public int a_compras_retencion_iva { get; set; }
        public int a_compras_retencion_islr { get; set; }
        public int a_pos_cuentas { get; set; }
        public int a_pos_comandas { get; set; }
        public int a_bancos { get; set; }
        public int a_bancos_movimientos { get; set; }
        public int a_bancos_movimientos_conceptos { get; set; }
        public int a_bancos_egreso { get; set; }
        public int a_contabilidad_plan_cuentas { get; set; }
        public int a_sistema_transito_asiento { get; set; }
        public int a_sistema_transito_asiento_numero { get; set; }
        public int a_vendedores { get; set; }
        public int a_bancos_beneficiarios { get; set; }
        public int a_vendedores_comisiones { get; set; }
        public int a_vendedores_comisiones_numero { get; set; }
        public int a_comanda1 { get; set; }
        public int a_comanda2 { get; set; }
        public int a_comanda3 { get; set; }
        public int a_cierre { get; set; }
        public int a_cxp_planifica { get; set; }
        public int a_pos_eventos { get; set; }
        public int a_compras_lista { get; set; }
        public int a_compras_recepcion { get; set; }
        public int a_productos_conteo { get; set; }
        public int a_productos_movimientos_recepcion { get; set; }
        public int a_empresa_sucursal { get; set; }
        public int a_cierre_ftp { get; set; }
        public int a_empresa_grupo { get; set; }
        public int a_usuarios_grupo { get; set; }
        public int a_productos_movimientos_traslados_dev { get; set; }
    }
}
