//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string auto { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string codigo { get; set; }
        public string auto_grupo { get; set; }
        public string estatus { get; set; }
        public string estatus_replica { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public System.DateTime fecha_baja { get; set; }
        public System.DateTime fecha_sesion { get; set; }
        public string apellido { get; set; }
    }
}
